### ISSUE TITLE
Error: Cannot find module 'bluetooth-hci-socket' /  Cannot find module: muse-lsl\node_modules\usb\src\binding\usb_bindings.node'

### ISSUE THREAD

**Issue by Amitpe** [urish/muse-lsl#3]
Hey, 
after performing all necessary steps, when trying to run I get this error: (Windows 8)

 Error: Cannot find module 'bluetooth-hci-socket'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (c:\projects\muse-lsl\node_modules\noble\lib\hci-socket\hci.js:6:26)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

Looks like the noble module doesn't recognize 'bluetooth-hci-socket' for some reason. tried to search that issue inside noble but didn't find any solution.
Any ideas?
Thanks

**Comment by Amitpe** [comment]
**update:**
After having installed[ SDK for Windows 8.1](https://developer.microsoft.com/en-us/windows/downloads/windows-8-1-sdk), I'm getting the following error, which is the same one I'm getting on my Windows 10 machine:

Error: Cannot find module 'c:\projects\muse-lsl\node_modules\usb\src\binding\usb_bindings.node'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (c:\projects\muse-lsl\node_modules\usb\usb.js:5:38)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by urish** [comment]
Hi Amit,

You can download the missing file from here: https://github.com/tessel/node-usb/releases.
For the latest node.js and a 64-bit system, get [this one](https://github.com/tessel/node-usb/releases/download/1.3.0/usb_bindings-v1.3.0-node-v57-win32-x64.tar.gz).

then simply extract the `usb_bindings.node` file and put it inside `node_modules\usb\src\binding` (you will probably have to create the `binding` directory inside `src` first). Good luck!

**Comment by Amitpe** [comment]
Works perfect. Thanks!
